[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
<<<<<<< HEAD
  status = 200


  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
=======
  status = 200
>>>>>>> e8a70bb (Working Project)
